### ISSUE TITLE
Ubuntu-AMD64.sh line 6: syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by LHC-kali** [AllPlatform/Termux-UbuntuX86_64#1]
![截屏_20200807_061251](https://user-images.githubusercontent.com/65726352/89587872-0da65800-d875-11ea-99e0-92fc4aa3f12d.jpg)

**Comment by AllPlatform** [comment]
wget https://raw.githubusercontent.com/AllPlatform/Termux-UbuntuX86_64/master/Ubuntu-AMD64.sh && bash Ubuntu-AMD64.sh

**Comment by LHC-kali** [comment]
谢谢回复😊😊

在 2020年9月8日星期二，AkiraYuki <notifications@github.com> 写道：

**Comment by LHC-kali** [comment]
I want to install the rootfs file I need myself. What to do to turn your Ubuntu script into your own rootfs

**Comment by AllPlatform** [comment]
I don't understand what you mean, do you translate Chinese into English correctly?

**Comment by AllPlatform** [comment]
i think you are in hong kong or taiwan

**Comment by LHC-kali** [comment]
我在China

在 2020年10月15日星期四，AkiraYuki <notifications@github.com> 写道：
