### ISSUE TITLE
libc-bin segmentation fault

### ISSUE THREAD

**Issue by absdevx** [AllPlatform/Termux-UbuntuX86_64#3]
Please i get this message, when i try to install something via apt. (Python3)

Get:8 http://archive.ubuntu.com/ubuntu focal/main amd64 python3 amd64 3.8.2-0ubuntu2 [47.6 kB]
Fetched 4793 kB in 12s (393 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Setting up libc-bin (2.31-0ubuntu9) ...
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault
dpkg: error processing package libc-bin (--configure):
 installed libc-bin package post-installation script subprocess returned error exit status 139
Errors were encountered while processing:
 libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by AllPlatform** [comment]
rm /var/lib/dpkg/info/$nomdupaquet* -f

**Comment by absdevx** [comment]
I've tried this but nothing

**Comment by AllPlatform** [comment]
rm /var/lib/dpkg/info/$nomdupaquet* -f
apt -f install

**Comment by TukangM** [comment]
> rm /var/lib/dpkg/info/$nomdupaquet* -f apt -f install

#6
